test_homepage:
    path:     /
    defaults: { _controller: TestBundle:Default:index }

# src/Test/PlatformBundle/Resources/config/routing.yml

hello_the_world:
    path:     /hello-world
    defaults: { _controller: TestBundle:Advert:index }
